apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - ingress.yaml
  - secrets.yaml
  # - node-disk-patch.yaml

patches:
- target:
    kind: Ingress
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-wave
      value: "150"
- target:
    kind: Secret
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "100"
- target:
    kind: DaemonSet
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "100"

# patchesStrategicMerge:
#   - node-disk-patch.yaml
