apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # - certificate.yaml
  - ingress.yaml

patches:   
- target:
    kind: Certificate
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "100"
- target:
    kind: Ingress
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-wave
      value: "150"
