apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cattle-system

resources:
  - ingress.yaml
  # - cluster-agent/

patches:
- target:
    kind: Ingress
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-wave
      value: "150"
